Extensions:
  DataExtend: enabled
  iniParser: 'default enabled — see core-config.yaml'
  Utilities: enabled

DataExtend:
  Import: DataExtend

Utilities:
  Import: mergeObjects, varToYaml, getLastModifiedInFolders, parseUrl, urlSpaceToUnderscore, liveSassCompiler