Extensions:
  ModuleLoader: 'Core module. It’s just annotation'
  iniParser: 'default enabled — see core-config.yaml'
  DataExtend: enabled
  Utilities: enabled

DataExtend:
  Import: DataExtend

Utilities:
  Import: mergeObjects, varToYaml, getLastModifiedInFolders, parseUrl, urlSpaceToUnderscore, liveSassCompiler