Extensions:
  # Disabling the “Image Handler” extension will turn off image processing features and gives static access to the shared/local images folders.
  # External images url-sources, which are stored in the Data Base cannot be used like as “/shared/images/imageName.ext” with disabled extension.
  ImageHandler: enabled