DROP SCHEMA IF EXISTS `users` ;
CREATE SCHEMA IF NOT EXISTS `users` DEFAULT CHARACTER SET utf8 COLLATE utf8_bin ;
SHOW WARNINGS;
DROP SCHEMA IF EXISTS `sharedAssets` ;

CREATE SCHEMA IF NOT EXISTS `sharedAssets` DEFAULT CHARACTER SET utf8 ;
SHOW WARNINGS;
USE `users` ;
DROP TABLE IF EXISTS `anonymousSessions` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `anonymousSessions` (
  `rowID` INT NOT NULL AUTO_INCREMENT,
  `sessionID` VARCHAR(256) NOT NULL,
  `settings` JSON NULL,
  PRIMARY KEY (`rowID`))
ENGINE = InnoDB;

SHOW WARNINGS;
CREATE UNIQUE INDEX `rowID_UNIQUE` ON `anonymousSessions` (`rowID` ASC) VISIBLE;

SHOW WARNINGS;
CREATE UNIQUE INDEX `sessionID_UNIQUE` ON `anonymousSessions` (`sessionID` ASC) VISIBLE;

SHOW WARNINGS;

DROP TABLE IF EXISTS `users` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `users` (
  `rowID` INT NOT NULL AUTO_INCREMENT,
  `userID` INT NOT NULL,
  `login` VARCHAR(256) NOT NULL,
  `password` VARCHAR(256) NOT NULL,
  `email` VARCHAR(256) NULL,
  `settings` JSON NULL,
  `authorize` JSON NULL,
  PRIMARY KEY (`rowID`))
ENGINE = InnoDB;

SHOW WARNINGS;
CREATE UNIQUE INDEX `rowID_UNIQUE` ON `users` (`rowID` ASC) VISIBLE;

SHOW WARNINGS;
CREATE UNIQUE INDEX `userID_UNIQUE` ON `users` (`userID` ASC) VISIBLE;

SHOW WARNINGS;
CREATE UNIQUE INDEX `login_UNIQUE` ON `users` (`login` ASC) VISIBLE;

SHOW WARNINGS;
CREATE UNIQUE INDEX `email_UNIQUE` ON `users` (`email` ASC) VISIBLE;

SHOW WARNINGS;
USE `sharedAssets` ;

DROP TABLE IF EXISTS `sharedFiles` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `sharedFiles` (
  `rowID` INT NOT NULL AUTO_INCREMENT,
  `FileType` VARCHAR(12) CHARACTER SET 'utf8' NOT NULL,
  `FileName` VARCHAR(92) NOT NULL,
  `FileLink` VARCHAR(256) NULL,
  `FileEmbedded` JSON NULL,
  `FileInfo` JSON NULL,
  `Title` VARCHAR(92) NULL,
  `TitleLocales` JSON NULL,
  `DescriptionLocales` JSON NULL,
  PRIMARY KEY (`rowID`))
ENGINE = InnoDB;

SHOW WARNINGS;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
